### ISSUE TITLE
感谢贡献，可以在 APIJSON 主页登记、群内宣传以获取大家关注哦

### ISSUE THREAD

**Issue by TommyLemon** [glennliao/apijson-go#1]
可以在 APIJSON 主项目 Tencent/APIJSON 首页 README#生态项目 加上这个项目，放在已登记但已经长期不维护的 apijson-go 项目前面
https://github.com/Tencent/APIJSON#%E7%94%9F%E6%80%81%E9%A1%B9%E7%9B%AE
<img width="880" alt="image" src="https://user-images.githubusercontent.com/5738175/196130233-8c34a8a3-a59c-4a23-8534-285facb0704c.png">

提交 PR 步骤可参考
https://github.com/Tencent/APIJSON/blob/master/CONTRIBUTING.md#pull-request
<img width="885" alt="image" src="https://user-images.githubusercontent.com/5738175/196132273-203cfe45-441a-4866-a601-a4792114e10e.png">

也可以在 APIJSON 技术群内分享，或者发文到掘金、开源中国、知乎等平台推广哦~

**Comment by glennliao** [comment]
@TommyLemon  等这两周再完善点， 可以出个案例了，就去登记啦😁
