### ISSUE TITLE
有没有项目上使用的例子呢

### ISSUE THREAD

**Issue by Coldxr** [glennliao/apijson-go#19]

**Comment by glennliao** [comment]
我在 https://github.com/glennliao/apijson-go-demo 更新了下最简例子（只写了查询），可以看下 （部分使用也有在这里的test目录下）。 目前我也是只在自己的个人项目中一边实践一边调整。 如何目前需要更多使用的例子，我再找时间 提供一个在线书签的小项目出来。 @Coldxr

**Comment by glennliao** [comment]
新增了一个https://github.com/glennliao/bookmark 书签系统的项目
